=== Ramnaik6791/academicportal/template/cours_temp/test.dtd
<!ELEMENT CSITcourses (course)*>
  <!ELEMENT course ( dept|course_title|ltp_dist|course_credits|ng_units|course_no|course_category|course_prereq|course_overlap|not_allowed|frequency|faculty|vis_faculty|course_objectives|course_contents|lecture_outline|tutorial_activities|practical_activities|selflearning_activities|reference|resources|design_content|date_of_approval_of_template_by_senate)*>  
  <!ATTLIST course id CDATA #REQUIRED>
  <!ELEMENT dept (#PCDATA)>  
  <!ELEMENT course_title (#PCDATA)>  
  <!ELEMENT ltp_dist (#PCDATA)>  
  <!ELEMENT course_credits (#PCDATA)>  
  <!ELEMENT ng_units (#PCDATA)>
  <!ELEMENT course_no (#PCDATA)>  
  <!ELEMENT course_category (IC|PLC|DC|DE|ISC|ISE|PC|PE|OC)*>  
  <!ELEMENT IC (#PCDATA)>
  <!ELEMENT PLC (#PCDATA)*>  
  <!ELEMENT DC (#PCDATA)*>  
  <!ELEMENT DE (#PCDATA)*>  
  <!ELEMENT ISC (#PCDATA)*>  
  <!ELEMENT ISE (#PCDATA)*> 
  <!ELEMENT PC (#PCDATA)*>  
  <!ELEMENT PE (#PCDATA)*>
  <!ELEMENT OC (#PCDATA)>   
  <!ELEMENT course_prereq (#PCDATA|ir)*>
  <!ELEMENT course_overlap (overlap_same_dep|overlap_other_dep|supersedes_existing)*>
  <!ELEMENT overlap_same_dep (#PCDATA|ir)*> 
  <!ELEMENT overlap_other_dep (#PCDATA|ir)*>
  <!ELEMENT supersedes_existing (#PCDATA|ir)*>
  <!ELEMENT not_allowed (#PCDATA)*> 
  <!ELEMENT frequency (#PCDATA)> 
  <!ELEMENT faculty (#PCDATA)>         
  <!ELEMENT vis_faculty (#PCDATA)>
  <!ELEMENT course_objectives (#PCDATA)> 
  <!ELEMENT course_contents (#PCDATA)>  
  <!ELEMENT lecture_outline ((module_no,Topic,No_of_hours)|(tot_lec_hr))*>
  <!ELEMENT module_no (#PCDATA)>  
  <!ELEMENT Topic (#PCDATA)> 
  <!ELEMENT No_of_hours (#PCDATA)> 
  <!ELEMENT tot_lec_hr (#PCDATA)> 
  <!ELEMENT tutorial_activities ((module_no2,description2,No_of_hours2)|(tot_tut_hr))*> 
  <!ELEMENT module_no2 (#PCDATA)> 
  <!ELEMENT description2 (#PCDATA)> 
  <!ELEMENT No_of_hours2 (#PCDATA)> 
  <!ELEMENT tot_tut_hr (#PCDATA)> 
  <!ELEMENT practical_activities ((module_no3,description3,No_of_hours3)|(tot_prac_hr))*> 
  <!ELEMENT module_no3 (#PCDATA)> 
  <!ELEMENT description3 (#PCDATA)> 
  <!ELEMENT No_of_hours3 (#PCDATA)> 
  <!ELEMENT tot_prac_hr (#PCDATA)> 
  <!ELEMENT selflearning_activities (module_no4,description4)*> 
  <!ELEMENT module_no4 (#PCDATA)> 
  <!ELEMENT description4 (#PCDATA)> 
  <!ELEMENT reference (#PCDATA)*>  
  <!ELEMENT resources (software|hardware|teaching_aids|lab|equipment|classroom|site|others)*>  
  <!ELEMENT software (#PCDATA)*>  
  <!ELEMENT hardware (#PCDATA)*>  
  <!ELEMENT teaching_aids (#PCDATA)*>  
  <!ELEMENT lab (#PCDATA)*>  
  <!ELEMENT equipment (#PCDATA)*>  
  <!ELEMENT classroom (#PCDATA)*>  
  <!ELEMENT site (#PCDATA)*>  
  <!ELEMENT others (#PCDATA)*>  
  <!ELEMENT design_content (design_prob|open_prob|project_type|open_lab|others2)*>
  <!ELEMENT design_prob (#PCDATA)*>  
  <!ELEMENT open_prob (#PCDATA)*>  
  <!ELEMENT project_type (#PCDATA)*>  
  <!ELEMENT open_lab (#PCDATA)*>  
  <!ELEMENT others2 (#PCDATA)*>
  <!ELEMENT date_of_approval_of_template_by_senate (#PCDATA)>  
  <!ELEMENT ir (#PCDATA)>
<!ATTLIST ir refid CDATA #REQUIRED>

=== Ramnaik6791/academicportal/template/cours_temp/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CSITcourses SYSTEM "test.dtd">
<CSITcourses>
	<course id="COL100">
		<dept>Computer Science and Engineering</dept>
		<course_title>Introduction to Computer Science</course_title>
		<ltp_dist>3-0-2</ltp_dist>
		<course_credits>4</course_credits>
		<ng_units>0</ng_units>
		<course_no>COL100</course_no>
		<course_category>
			<IC>YES</IC>
			<PLC></PLC>
			<DC></DC>
			<DE></DE>
			<ISC></ISC>
			<ISE></ISE>
			<PC></PC>
			<PE></PE>
			<OC>NO</OC>
		</course_category>
		<course_prereq></course_prereq>
		<course_overlap>
			<overlap_same_dep></overlap_same_dep>
			<overlap_other_dep></overlap_other_dep>
			<supersedes_existing><ir refid="CSL101">CSL101</ir><ir refid="CSL102">CSL102</ir></supersedes_existing>
		</course_overlap>
		<not_allowed>NA</not_allowed>
		<frequency>EVERY SEM</frequency>
		<faculty></faculty>
		<vis_faculty>NO</vis_faculty>
		<course_objectives>Introduction to algorithmic problem solving. Introduction to design and analysis of correct, efficient and maintain able programs.</course_objectives>
		<course_contents>Concept of an algorithm; termination and correctness. Algorithms to programs: specification, top-down development and stepwise refinement. Iterative versus recursive style; problem solving using a functional style; correctness issues in programming; efficiency issues in programming; time and space measures. Structured style of imperative programming; programming in an imperative language using advanced features: procedures, functions. Data types, representational invariants. Encapsulation, abstractions, interaction, modularity. Identifying and exploiting inherent concurrency.  </course_contents>
		<lecture_outline>
			<module_no>1</module_no>
			<Topic>top="Models of computation. The stored program model. 
				Mathematical preliminaries 
				Computer Organization and Basic Principles of Operation 
				A functional model of computation 
				The primitive expressions 
				Function parameter substitution and variable binding 
				Definition of functions using case analysis" lec="5"</Topic>
			<No_of_hours>4</No_of_hours>
			<module_no>2</module_no>
			<Topic>Functions as inductively defined computational processes
				Recursive processes
				Analysis of correctness and efficiency
				Tail-recursion and iterative processes
				Correctness of an iterative process
				Examples of iterative processes</Topic>
			<No_of_hours>6</No_of_hours>
			<module_no>3</module_no>
			<Topic>Analysis of correctness and efficiency
Correctness
Efficiency
Asymptotic analysis and Orders of growth
More examples of recursive algorithms
</Topic>
			<No_of_hours>5</No_of_hours>
			<module_no>4</module_no>
			<Topic>Linear Data Structures:
Lists, Arrays, Strings      
Sequence Operations
Stacks and queues
Searching &amp; Sorting
Hashes &amp;  Advanced Data Structures
</Topic>
			<No_of_hours>5</No_of_hours>
			<module_no>5</module_no>
			<Topic>Programming Language</Topic>
			<No_of_hours>8</No_of_hours>
			<module_no>6</module_no>
			<Topic>Executable specifications and rapid-prototyping
Examples of step-wise refinement
Identifying and exploiting inherent concurrency. Concurrency and Multithreaded computations
</Topic>
			<No_of_hours>4</No_of_hours>
			<module_no>7</module_no>
			<Topic>Introduction to numerical computing</Topic>
			<No_of_hours>3</No_of_hours>
			<module_no>8</module_no>
			<Topic>Procedural abstraction using higher order functions. Example of large size problem solving using procedural abstraction and step wise refinement. Examples to be drawn from graphics, games, encryption, web applications, etc.	</Topic>
			<No_of_hours>7</No_of_hours>
			<tot_lec_hr>42</tot_lec_hr>
		</lecture_outline>
		<tutorial_activities>

		</tutorial_activities>
		<practical_activities>
			<module_no3>1</module_no3>
			<description3>Multiple Programming Assignments in a modern high level programming language such as Python, ML, OCAML, C, C++ of varying difficulty </description3>
			<No_of_hours3>28</No_of_hours3>
			<tot_prac_hr>28</tot_prac_hr>
		</practical_activities>
		<selflearning_activities></selflearning_activities>
		<reference>1.	Structure and Interpretation of Computer Programs by Harold Abelson and Gerald Sussman with Julie Sussman, MIT Press, 1985.
2.	How to solve it by Computer by R. J. Dromey, Prentice-Hall India EEE Series.
3.	Subashish Banerjee, Lecture Notes in Computer Science, 2011</reference>
		<resources>
			<software>Python, OCAML , C++ development environments </software>
			<hardware>Computer Terminal for all the students</hardware>
			<lab>First Year Teaching Labs in New Lecture Complex</lab>
			<classroom>Data Projector</classroom>
		</resources>
		<design_content>
			<design_prob>20%</design_prob>
			<project_type>20%</project_type>
			<others2>60%</others2>
		</design_content>
	</course>
</CSITcourses>
